encoder: resnet18
attention: noam
coam_layer_data: [3, None, None]
lr: 0.0001
weight_decay: 0.0005
batch_size: 18
test_batch_size: 18
num_dataloader_workers: 8
classes: 2
model_save_path: /content/gdrive/Shareddrives/CV Project/The-Change-You-Want-to-See-Segmentation/checkpoints
datasets:
  train_dataset:
    name: second_train
    class: SecondDataset
    args:
      path_to_dataset: /content/gdrive/Shareddrives/CV Project/second_dataset/SECOND_train_set
      split: "train"
      method: "segmentation"
      image_size: 256
      image_transformation: "affine"
  val_dataset:
    name: second_val
    class: SecondDataset
    args:
      path_to_dataset: /content/gdrive/Shareddrives/CV Project/second_dataset/SECOND_train_set
      split: "val"
      method: "segmentation"
      image_size: 256
      image_transformation: "affine"
  test_datasets:
    - name: second_test
      class: SecondDataset
      args:
        path_to_dataset: /content/gdrive/Shareddrives/CV Project/second_dataset/test
        split: "test"
        method: "segmentation"
        image_size: 256
        image_transformation: "affine"